safe: false

# build settings
markdown: kramdown
highlighter: rouge
lsi: false
permalink: /:title

title: "Life's AWESOME"
description: "개발과 음악 자기반성"
baseurl: ""
url: "http://blindlee1324.github.com" # replace by your site's url
twitter_username: ya_doka_ri
github_username:  blindlee1324 # (your name)
accent: "#f7f7e6" # accent color for blog column

author: "Yun Lee"
address: "부산광역시"
email: "aldltekd@naver.com"

# google analytics tracking code, please change the value
g_analytics: "UA-117100627-1"

# language settings
isolang: ko

# exclude files
exclude:
  - LICENSE
  - README.md
